#!  Dockerfile for the App

FROM node:lts-alpine 

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install

COPY . .

EXPOSE 3000

CMD [ "pnpm", "run", "dev" ]
