 # Spécifie la version de Docker Compose

services:
  # !Configuration du service de l'application Node.js
  app:  # Définition du service pour l'application
    build:  # Configuration de la construction de l'image Docker
      context: .  # Contexte de construction : le répertoire courant
      dockerfile: Dockerfile.dev  # Utilisation du Dockerfile.dev pour la construction
    ports:
      - "3000:3000"  # Exposition du port 3000 de l'hôte vers le conteneur
    container_name: pet-foster-connect-app-dev  # Nom du conteneur pour l'application
    env_file:
      - .env  # Chargement des variables d'environnement à partir du fichier .env
    depends_on:
      - db  # L'application dépend du service 'db' (base de données)
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules  # Monté le répertoire courant dans le conteneur

 # !Configuration du service de base de données PostgreSQL
  db:  
    image: postgres  # Utilisation de l'image officielle de PostgreSQL
    container_name: pet-foster-connect-db-dev  
    ports:
      - "5433:5432"
    env_file:
      - .env  # Chargement des variables d'environnement à partir du fichier .env
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/  # Monté le répertoire 'data' pour initialiser la DB
      - pet-foster-connect-volume-dev:/var/lib/postgresql/data  # Volume pour persister les données de la DB

volumes:
  pet-foster-connect-volume-dev:  # Définition d'un volume persistant pour PostgreSQL
