### --------------Lister toutes les alertes-----------------
###! SANS TOKEN
GET http://localhost:3000/api/ask


###* AVEC TOKEN
GET http://localhost:3000/api/ask
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJhbGljZS5iZXJuYXJkQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTQ4NzQ4NywiZXhwIjoxNzMxNDkxMDg3fQ.04148tRpkxGKG1a4DUMTHBaO87qdL4Z1U8OXdw-LpjY

#---------------Obtenir le détail d'une alerte -----------

###! SANS TOKEN
GET http://localhost:3000/api/ask/3


###* AVEC TOKEN 
GET http://localhost:3000/api/ask/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJhbGljZS5iZXJuYXJkQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTQ4NzQ4NywiZXhwIjoxNzMxNDkxMDg3fQ.04148tRpkxGKG1a4DUMTHBaO87qdL4Z1U8OXdw-LpjY


#---------------Créer une nouvelle alerte -----------------------

###  ! SANS TOKEN
POST http://localhost:3000/api/ask
Content-Type: application/json

{
  "id_family": 3,
  "id_animal": 9
}

###* AVEC TOKEN
POST http://localhost:3000/api/ask
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsImVtYWlsIjoiYWxpY2UuZGF2aWRAZW1haWwuY29tIiwicm9sZSI6ImZhbWlseSIsImlhdCI6MTczMzg2MDc5MiwiZXhwIjoxNzMzODY0MzkyfQ.RcEuXLiw92Mbl-9IVikvgsiyz5VEhA4Ydy3A9PMmCEA
Content-Type: application/json

{
  "id_family": 15,
  "id_animal": 3
}

#------------------Modifier une alerte--------------------------

### !  SANS TOKEN
PATCH http://localhost:3000/api/ask/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJwaWVycmUuZHVib2lzQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMzg2MTMzOSwiZXhwIjoxNzMzODY0OTM5fQ.xcnrYicCthYH3FoSLx361sI6rvHFHoG1tkZi2Nmu7Mw
Content-Type: application/json

{
  "status": "validée"
}



