### ---------Récupérer toutes les familles-(admin asso)--------------
#! SANS TOKEN
GET http://localhost:3000/api/family
Accept: application/json


###* AVEC TOKEN
GET http://localhost:3000/api/family
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJtYXJpZS5sZWZlYnZyZUBlbWFpbC5jb20iLCJyb2xlIjoiYXNzb2NpYXRpb24iLCJpYXQiOjE3MzE0Mzk3NTEsImV4cCI6MTczMTQ0MzM1MX0.r3nR926PDl3lBiseRg4BO7SKC8MnPHPURCvVTWzl2gk
Accept: application/json

#----------------Récupérer une famille par son ID (admin asso)----------------

###! SANS TOKEN
GET http://localhost:3000/api/family/35
Accept: application/json


### AVEC TOKEN
GET http://localhost:3000/api/family/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsImVtYWlsIjoiamVzc21lbnpvQGplc3MuZnIiLCJyb2xlIjoiZmFtaWx5IiwiaWF0IjoxNzMyNzg0MDg4LCJleHAiOjE3MzI3ODc2ODh9.anyn_S5oil4Z8acdZOvvt_AOZPTPLp40-ysS6-WHeT0
Accept: application/json

### modification d'une family
PATCH http://localhost:3000/api/family/18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqZWFuLmR1cG9udEBlbWFpbC5jb20iLCJyb2xlIjoiZmFtaWx5IiwiaWF0IjoxNzMyNjIzODc1LCJleHAiOjE3MzI2Mjc0NzV9.LvAO9Gjyx-5pD9dt-7RyibzlTK4Z1xJzWKgXOMJyDMo

{
    
"address": "123 Rue de la Pluie",
"city": "Parici",
"phone": "0987654321",
"postal_code": "75000",
"imageUrl": "https://cdn.brazil-selection.com/wp-content/uploads/2022/03/animaux-du-bresil-slide-1024x925.webp",
"user": {
     "currentPassword": "Fa@78mily",
        "newPassword": "Menzo0607?",
        "confirmPassword": "Menzo0607?"

}

}

### Suppression d'une family
DELETE http://localhost:3000/api/family/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzE0MTc4MjksImV4cCI6MTczMTQyMTQyOX0.iMjaGmmJyYJshydelxMHwLmWNVo6u3D_k5bjQX4UADA
Content-Type: application/json